version: '3.7'
services:
  shorty:
    container_name: shorty
    build: .
    entrypoint: ./.docker/start.sh
    volumes:
      - .:/home/node/app
    ports:
      - 5510:3000
    depends_on:
      - db
    networks:
      - net-shorty

  db:
    container_name: db
    image: mongo
    restart: on-failure
    volumes:
      - ./.docker/dbdata:/data/db
      - ./.docker/mongo:/docker-entrypoint-initdb.d
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
      - MONGO_INITDB_DATABASE=app
    networks:
      - net-shorty

  mongo-express:
    container_name: mongo-express
    image: mongo-express
    restart: always
    ports:
      - 5511:8081
    environment:
      - ME_CONFIG_MONGODB_SERVER=db
      - ME_CONFIG_MONGODB_AUTH_USERNAME=root
      - ME_CONFIG_MONGODB_AUTH_PASSWORD=root
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=root
    depends_on:
      - db
    networks:
      - net-shorty
  redis:
    image: redis
    restart: always
    command: redis-server
    hostname: redis
    volumes:
      - ./.docker/redis:/data

  redis-commander:
    hostname: redis-commander
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
      - REDIS_HOSTS=redis
      - REDIS_HOST=redis
      - REDIS_PORT=redis:6379
      - REDIS_PASSWORD=admin123
      - HTTP_USER=root
      - HTTP_PASSWORD=root
    ports:
      - "5518:8081"
    depends_on:
      - redis

networks:
  net-shorty:
    driver: bridge
